- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - set_fact:
        ami_id: ami-d41d58a7
    - name: Provision a set of instances
      ec2:
         key_name: tszpinda-ir
         region: eu-west-1
         group: ssh-on-22-all-source
         instance_type: t2.micro
         image: "{{ ami_id }}"
         wait: true
         exact_count: 3
         count_tag:
            Name: ansible
         instance_tags:
            Name: ansible
      register: ec2
    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: utility
        ansible_ssh_user: ec2-user
      with_items: ec2.instances

- hosts: tag_Name_ansible
  tasks:
    - name: ping pong
      ping:

- hosts:  utility
  tasks:
    - name: ping pong
      ping:
