- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - set_fact:
        ami_id: ami-d41d58a7
        amazon_tag: ansible
    - name: Provision a set of instances
      ec2:
         key_name: tszpinda-ir
         region: eu-west-1
         group: ssh-on-22-all-source
         instance_type: t2.micro
         image: "{{ami_id}}"
         wait: true
         exact_count: 1
         count_tag:
            Name: "{{amazon_tag}}"
         instance_tags:
            Name: "{{amazon_tag}}"
      register: ec2
    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: tag_Name_ansible
        ansible_ssh_user: ec2-user
      with_items: ec2.instances
      when: item.state == 'running' or item.state == 'started'
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=10 timeout=320 state=started
      with_items: "{{ec2.instances}}"
      when: item.state == 'running' or item.state == 'started'
    - name: refresh inventory
      meta: refresh_inventory



- hosts: tag_Name_ansible
  gather_facts: True
  tasks:
    - name: ping pong
      ping:

