---
- name: ensure database is created
  postgresql_db:
    name: "{{dbname}}"
    port: 7432
    login_host: "localhost"
    login_user: "{{scmDbUser}}"
    login_password: "{{scmDbPassword}}"

- name: ensure user has access to database
  postgresql_user:
    db: "{{dbname}}"
    name: "{{dbuser}}"
    password: "{{dbpassword}}"
    priv: ALL
    port: 7432
    login_host: "localhost"
    login_user: "{{scmDbUser}}"
    login_password: "{{scmDbPassword}}"

- name: ensure user does not have unnecessary privilege
  postgresql_user:
    db: "{{dbname}}"
    name: "{{dbuser}}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    port: 7432
    login_host: "localhost"
    login_user: "{{scmDbUser}}"
    login_password: "{{scmDbPassword}}"

- name: ensure no other user can access the database
  postgresql_privs:
    db: "{{dbname}}"
    role: PUBLIC
    type: database
    priv: ALL
    state: absent
    port: 7432
    login_host: "localhost"
    login_user: "{{scmDbUser}}"
    login_password: "{{scmDbPassword}}"