---
- set_fact:
    zookeeperHost1Id: "588a636b-2d27-4589-a1f9-3ea9dbf292a8"

- name: zookeeper service setup
  include: service-setup.yml
  vars:
    service_name: zookeeper
    role_groups: ["server"]

- name: zookeeper service start
  include: service-start.yml
  vars:
      service_name: zookeeper