---
- name: cloudera agent requires 127.0.0.1 to not point and fqdn
  lineinfile: dest=/etc/hosts regexp="^127.0.0.1" line="127.0.0.1 localhost"
  tags: hosts-config

- name: cloudera agent requires ::1 to not point and fqdn
  lineinfile: dest=/etc/hosts regexp="^::1" line="::1 localhost"
  tags: hosts-config

- name: cloudera /etc/resolv.conf
  lineinfile: dest=/etc/resolv.conf line="search {{cloudera_domain}}"
  tags: hosts-config

- name: /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts force=yes backup=yes
  tags: hosts-config